name: Solution Build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
          dotnet-quality: "preview"

      - name: restory
        run: dotnet restore

      - name: build
        run: dotnet build

      - name: test
        run: dotnet test --no-restore --no-build
