name: Desktop publish to release

# 推送tag时触发
on:
  push:
    tags:
      - Desktop_v**
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version From Tag
        uses: olegtarasov/get-tag@v2.1.3
        id: Tag
        with:
          tagRegex: "(?<Name>)_v(?<Version>)"

      - name: Show Tag
        shell: pwsh
        run: echo "$steps.Tag"

      # - uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: "9.0.x"
      #     dotnet-quality: "preview"

      # - name: restory
      #   run: dotnet restore

      # - name: build
      #   run: dotnet build

      # - name: test
      #   run: dotnet test --no-restore --no-build

      # - name: cd Desktop
      #   run:

      # - name: publish
      #   working-directory: ./OneProject.Dekstop
      #   run: dotnet publish -c Release --no-build --no-restore -o ./${{steps.Tag.outputs.Name}}_${{steps.Tag.outputs.Version}}

      # - name: zip
      #   uses: thedoctor0/zip-release@0.7.5
      #   with:
      #     type: zip
      #     filename: ${{env.FileName}}.zip
      #     path: ${{env.FileName}}

      # - name: push release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "${{env.FileName}}.zip"
      #     token: ${{secrets.RELEASE_TOKEN}}
